"""
Django settings for backend_repuesto_autos project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #agregacion app nueva ani
    
    'productos',
    'usuarios',
    'pedidos',

]

# Configuración de la autenticación
LOGIN_REDIRECT_URL = '/'  # Redirige al home o la URL que elijas después de iniciar sesión

LOGIN_URL = 'login'  # Si el usuario no está autenticado, será redirigido aquí

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_repuesto_autos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',  #activar solo si se utiliza un templates global
            BASE_DIR / 'backend/usuarios/templates',  # path correcto de templates de usuarios
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_repuesto_autos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Para PostgreSQL
        'NAME': env('DB_NAME'),       # Nombre de tu base de datos en PostgreSQL
        'USER': env('DB_USER'),                # Usuario de PostgreSQL
        'PASSWORD': env('DB_PASSWORD'),                # Contraseña del usuario
        'HOST': env('DB_HOST'),                        # Usualmente 'localhost' para desarrollo local
        'PORT': env('DB_PORT', default='5432'),                             # Puerto por defecto de PostgreSQL
        'OPTIONS': {
            'options': '-c client_encoding=UTF8'
        }
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Configuración de correo electrónico para enviar correos de verificación

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' #linea activada si estas en desarrollo y no quieres enviar correos reales, puedes usar este backend de consola
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  #activar esta linea cuando la app este en uso y ya tenga su email en el servidor del dominio, y desactivar la linea de arriba

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Utiliza SMTP en producción
EMAIL_HOST = 'smtp.gmail.com'  # El servidor SMTP de Gmail
EMAIL_PORT = 587  # Puerto de Gmail
EMAIL_USE_TLS = True  # Usar TLS para seguridad
EMAIL_HOST_USER = env('EMAIL_HOST_USER')  # Tu correo de Gmail
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')  # La contraseña de aplicación generada en Google
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')  # Correo desde el cual se envían los correos




# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



